version: "3"
services:
  app:
    container_name: admin-template
    image: irolegroup/admin-express
    environment:
      - DatabaseUrl=mongodb://mongo:27017/iRole-Express-Admin
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
